site_name: mklists
pages:
    - Home: 'index.md'
    - History: 'history.md'
    - Wish List: 'wishlist.md'
site_url: http://mklists.com
repo_url: https://github.com/tombaker/mklists
repo_name: 'Github'
edit_uri: 'edit/master/docs/'
site_description: 'mklists: a GTD-style manager of plain-text lists based on configurable rules'
remote_branch: gh-pages
theme: readthedocs
