"""move_datafiles_to_backupdir()

Edit /Users/tbaker/github/tombaker/mklists/mklists/backups.py
"""

import os
from mklists.backups import move_datafiles_to_backupdir


def test_backups_move_datafiles_to_backupdir(tmpdir):
    """Function move_datafiles_to_backupdir() uses output of
    make_backupdir_pathname(), emulated here by assembling the
    backupdir_pathname from its components:

    * make_backupdir_pathname:reporoot_pathname => here: tmpdir
      * default: generated by get_rootdir_pathname()
    * make_backupdir_pathname:backups_dirname   => here: backups
      * default: backups:BACKUPDIR_NAME
    * make_backupdir_pathname:backup_shortname  => here: shortname
      * default: generated by make_backup_shortname()
    * make_backupdir_pathname:timestamp_name    => here: timestamp
      * default: backups:TIMESTAMP_STR

    """
    backups = ".backups"
    shortname = "agenda"
    timestamp = "2019-07-26_0758_06488910"
    tmpdir_backupdir = tmpdir.mkdir(backups)
    tmpdir_backupdir_agenda = tmpdir_backupdir.mkdir(shortname)
    backupdir_fullpath = tmpdir_backupdir_agenda.mkdir(timestamp)
    tmpdir_agendadir = tmpdir.mkdir(shortname)
    tmpdir_agendadir.join("file_a").write("some content")
    tmpdir_agendadir.join("file_b").write("some content")
    os.chdir(tmpdir_agendadir)
    ls_agendadir_before = sorted(os.listdir())
    move_datafiles_to_backupdir(
        ls_datadir_filenames=ls_agendadir_before, backupdir_pathname=backupdir_fullpath
    )
    ls_agendadir_after = sorted(os.listdir())
    os.chdir(backupdir_fullpath)
    expected = ["file_a", "file_b"]
    ls_backupdir_agenda = sorted(os.listdir())
    print(f"ls_agendadir_before = {ls_agendadir_before}")
    print(f"expected = {expected}")
    print(f"ls_backupdir_agenda = {ls_backupdir_agenda}")
    assert ls_backupdir_agenda == expected
    assert ls_agendadir_after == []
