project = "mklists"
copyright = "2020, Tom Baker"
author = "Tom Baker"
release = "0.2"
extensions = []
templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "default"
github_project_url = "https://github.com/tombaker/mklists"
html_static_path = ["_static"]
